apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-notsleep-to-httpbin
spec:
  podSelector:
    matchLabels:
      app: notsleep 
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: httpbin 
