# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "fedora/36-cloud-base"
  config.vm.disk :disk, size: "40GB", primary: true

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 31000, host: 31000 

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Istio dev, port 1313 is used for the UI local dev
  config.vm.network "forwarded_port", guest: 1313, host:1313, host_ip: "127.0.0.1"
  #
  # Cluster 1 app NodePorts 
  config.vm.network "forwarded_port", guest: 31000, host: 31000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 31001, host: 31001, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 31002, host: 31002, host_ip: "127.0.0.1"
  # Cluster 1 addons (Prometheus etc) 
  config.vm.network "forwarded_port", guest: 31100, host: 31100, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 31101, host: 31101, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 31102, host: 31102, host_ip: "127.0.0.1"
  # Cluster 2 app NodePorts 
  config.vm.network "forwarded_port", guest: 32000, host: 32000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 32001, host: 32001, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 32002, host: 32002, host_ip: "127.0.0.1"
  # Cluster 2 addons (Prometheus etc) 
  config.vm.network "forwarded_port", guest: 32100, host: 32100, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 32101, host: 32101, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 32102, host: 32102, host_ip: "127.0.0.1"
  # For Prometheus 
  ##CHANGEconfig.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1"
  # For Grafana 
  ##CHANGEconfig.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  # For Kiali 
  ##CHANGEconfig.vm.network "forwarded_port", guest: 20001, host: 20001, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  config.vm.synced_folder "/Users/srampal/repos/", "/home/vagrant/repos"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

config.vm.provider "virtualbox" do |v|
  v.memory = 20000 
  v.cpus = 4
#  v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
# sync time every 10 seconds
        v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-interval", 10000 ]
        # adjustments if drift > 100 ms
        v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-min-adjust", 100 ]
        # sync time on restore
        v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore", 1 ]
        # sync time on start
        v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-start", 1 ]
        # at 1 second drift, the time will be set and not "smoothly" adjusted
        v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ] 
end

  config.vm.hostname = "ambient-vm"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  #config.vm.provision :shell, path: "stub-bootstrap.sh"
  #config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/New_York /etc/localtime", run: "always"

end
