kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
networking:
    ipFamily: "ipv4"
    podSubnet: "10.1.0.0/16"
    serviceSubnet: "10.2.0.0/16"
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 31000
      hostPort: 31000
      listenAddress: "0.0.0.0"
      protocol: tcp
  extraMounts:
  - hostPath: /home/vagrant/repos/github.com/kubernetes-sigs/kpng/backends/ebpf/bpf/
    containerPath: /bpf
  - hostPath: /home/vagrant/repos/github.com/ebpf-networking/tc-nodeport/
    containerPath: /tcnp
