kind: Cluster
name: amb1
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
    extraPortMappings:
    - containerPort: 31000
      hostPort: 31000
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 31001
      hostPort: 31001
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 31002
      hostPort: 31002
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32000
      hostPort: 32000
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32001
      hostPort: 32001
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32002
      hostPort: 32002
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 31100
      hostPort: 31100
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 31101
      hostPort: 31101
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 31102
      hostPort: 31102
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32100
      hostPort: 32100
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32101
      hostPort: 32101
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32102
      hostPort: 32102
      listenAddress: "0.0.0.0"
      protocol: TCP
networking:
  podSubnet: 10.240.0.0/16
  serviceSubnet: 10.110.0.0/16
