kind: Cluster
name: cluster1
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
    - containerPort: 31000
      hostPort: 31000
      listenAddress: "0.0.0.0"
      protocol: TCP
networking:
  podSubnet: 10.240.0.0/16
  serviceSubnet: 10.110.0.0/16
