FROM nvcr.io/nvidia/cuda:12.4.1-cudnn-devel-ubi9
RUN dnf update -y && \
    dnf install -y python3-pip python3-devel \
        git vim zlib-devel libxml2-devel gcc g++
    
WORKDIR /src
RUN git clone https://github.com/openai/triton.git && \
    cd triton && \
    pip install ninja cmake wheel pybind11
WORKDIR /src/triton
# Build and install triton
RUN pip install -e python
# Tutorial pre-reqs
RUN pip install torch pytest
RUN pip install -e './python[tutorials]'

